module.exports = {


    ra: {
        action: {
            add_filter: 'Pridaj filter',
            add: 'Pridaj',
            back: 'Späť',
            bulk_actions: '1 záznam označený |||| %{smart_count} záznamy označené |||| %{smart_count} záznamov označených',
            cancel: 'Zruš',
            clear_input_value: 'Vymazať',
            clone: 'Kopírovať',
            confirm: "Potvrdiť",
            create: 'Vytvoriť',
            delete: 'Zmazať',
            edit: 'Upraviť',
            export: 'Exportovať',
            list: 'Zoznam',
            refresh: 'Obnoviť',
            remove_filter: 'Odober filter',
            remove: 'Odstrániť',
            save: 'Uložiť',
            search: "Hľadať",
            show: 'Ukázať',
            sort: 'Zotriediť',
            undo: 'Vrátiť zmeny',
            unselect: 'Odznačiť',
            expand: 'Rozbaliť',
            close: 'Zavrieť',
            open_menu: 'Otvor menu',
            close_menu: 'Zavri menu',
        },
        boolean: {
            true: 'Áno',
            false: 'Nie',
            null: '',
        },
        page: {
            create: 'Vytvor %{name}',
            dashboard: 'Prehľad',
            edit: '%{name} #%{id}',
            error: 'Nastala chyba',
            list: 'Všetky %{name}',
            loading: 'Načítavam',
            not_found: 'Nenájdené',
            show: '%{name} #%{id}',
            empty: 'Žiadne záznamy',
            invite: 'Pozvať',
        },
        input: {
            file: {
                upload_several: 'Pretiahnite súbory pre nahranie alebo kliknite a vyberte.',
                upload_single: 'Pretiahnite súbor pre nahranie alebo kliknite a vyberte.',
            },
            image: {
                upload_several: 'Pretiahnite obrázky pre nahranie alebo kliknite a vyberte.',
                upload_single: 'Pretiahnite obrázok pre nahranie alebo kliknite a vyberte.',
            },
            references: {
                all_missing: 'Odkazované dáta neboli nájdené.',
                many_missing: 'Niektoré z príslušných odkazov už nie sú k dispozícií.',
                single_missing: 'Príslušný odkaz už nie sú k dispozícií.',
            },
            password: {
                toggle_visible: 'Skryť heslo',
                toggle_hidden: 'Ukázať heslo',
            },
        },
        message: {
            about: 'O',
            are_you_sure: 'Ste si istí?',
            bulk_delete_content: 'Ste si istí, že chcete zmazať záznam typu %{name}? |||| Ste si istí, že chcete zmazať %{smart_count} záznamy typu %{name}? |||| Ste si istí, že chcete zmazať %{smart_count} záznamov?',
            bulk_delete_title: 'Zmazať záznam |||| Zmazať %{smart_count} záznamy |||| Zmazať %{smart_count} záznamov',
            delete_content: 'Ste si istí, že chcete zmazať tento záznam?',
            delete_title: 'Zmazať %{name} #%{id}',
            details: 'Detaily',
            error: "Vyskytla sa chyba a Váša požiadavka nemohla byť naplnená.",
            invalid_form: 'Formulár nie je platný, skontrolujte chyby.',
            loading: 'Stránka sa načítava, počkajte prosím.',
            no: 'Nie',
            not_found: 'Zadali ste zlú adresu URL alebo link.',
            yes: 'Áno',
            unsaved_changes: 'Niektoré zmeny neboli uložené, naozaj chcete pokračovať?',
        },
        navigation: {
            no_results: 'Žiadne výsledky',
            no_more_results: 'Číslo strany (%{page}) je za rozsahom. Skúste predchádzajúce strany.',
            page_out_of_boundaries: 'Číslo strany (%{page}) je mimo rozsah.',
            page_out_from_end: 'Nemožno ísť za poslednú stranu',
            page_out_from_begin: 'Nemožno ísť pred prvú stranu',
            page_range_info: '%{offsetBegin}-%{offsetEnd} z %{total}',
            page_rows_per_page: 'Záznamy na strane:',
            next: 'Ďalšia',
            prev: 'Predošlá',
        },
        auth: {
            auth_check_error: 'Pre pokračovanie sa prihláste, prosím.',
            user_menu: 'Profil',
            username: 'Užívateľské meno',
            password: 'Heslo',
            sign_in: 'Prihlásiť',
            sign_in_error: 'Overenie zlyhalo, skúste to znova',
            logout: 'Odhlásiť',
        },
        notification: {
            updated: 'Záznam aktualizovaný |||| %{smart_count} záznamov aktualizovaných',
            created: 'Záznam vytvorený',
            deleted: 'Záznam zmazaný |||| %{smart_count} záznamov zmazaných',
            bad_item: 'Nesprávny záznam',
            item_doesnt_exist: 'Záznam neexistuje',
            http_error: 'Chyba komunikácie zo serverom',
            data_provider_error: 'Chyba poskytovateľa dát. Skontrolujte výstup z konzoly.',
            i18n_error: 'Chyba prekladu pre zvolený jazyk.',
            canceled: 'Akcia zrušená',
            logged_out: 'Pripojenie vypršalo. Pripojte sa znovu.',
        },
        validation: {
            required: 'Požadovaný',
            minLength: 'Musí byť najmenej %{min} znakov',
            maxLength: 'Môže byť najviac %{max} znakov',
            minValue: 'Musí byť najmenej %{min}',
            maxValue: 'Môže byť najviac %{max}',
            number: 'Musí byť číslo',
            email: 'Musí byť valídna emailová adresa',
            oneOf: 'Musí byť jedno z: %{options}',
            regex: 'Musí spĺňať špecifický formát (regexp): %{pattern}',
        },
    },
};
